modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mixins]]
config="battlecraft.mixins.json"

[[mods]]
modId="battlecraft"
version="${mod_version}"
displayName="BattleCraft - Core"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.battlecraft]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.battlecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="airdrop"
version="${mod_version}"
displayName="BattleCraft - AirDrop"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.airdrop]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.airdrop]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="capturepoints"
version="${mod_version}"
displayName="BattleCraft - Capture Points"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.capturepoints]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.capturepoints]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="dmgndctr"
version="${mod_version}"
displayName="BattleCraft - Damage Indicator"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.dmgndctr]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.dmgndctr]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="itemmodifiers"
version="${mod_version}"
displayName="BattleCraft - Item Modifiers"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.itemmodifiers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.itemmodifiers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="killreward"
version="${mod_version}"
displayName="BattleCraft - Kill Reward"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.killreward]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.killreward]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="knockdown"
version="${mod_version}"
displayName="BattleCraft - KnockDown"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.knockdown]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.knockdown]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="combattimer"
version="${mod_version}"
displayName="BattleCraft - Combat Timer"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.combattimer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.combattimer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="quarrymod"
version="${mod_version}"
displayName="BattleCraft - Quarry"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.quarrymod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.quarrymod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="sellmod"
version="${mod_version}"
displayName="BattleCraft - Sell"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.sellmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.sellmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="immortality"
version="${mod_version}"
displayName="BattleCraft - Immortality"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.immortality]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.immortality]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mods]]
modId="minimap"
version="${mod_version}"
displayName="BattleCraft - Minimap"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.minimap]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.minimap]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
